@server = http://localhost:8080
###
GET {{server}}/api/instrumento
###
POST {{server}}/api/instrumento
Content-Type: application/json

{"firstName": "Mi", "lastName": "Aplicación", "description": "React"}